In [ ]:
import cv2
import numpy as np 
import face_recognition
import os 
from datetime import datetime

path = 'imagesattendes'
images =[]
classNames = []
myList = os.listdir(path)
for cl in myList:
    curImg = cv2.imread(f'{path}/{cl}')
    images.append(curImg)
    classNames.append(os.path.splitext(cl)[0])
print(classNames)

#function pour incoder notre images

def findEncodings(images):
    endodeList = []
    for img in images : 
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        encode= face_recognition.face_encodings(img)[0]
        endodeList.append(encode)
    return endodeList

#function to save name and date when it reads it 

def markAttendance(name):
    with open('Attendances.csv' , 'r+') as f :
        MyDataList = f.readlines()
        nameList = []
        for line in MyDataList : 
            entry = line.split(';')
            nameList.append(entry[0])
        if name not in nameList:
            now= datetime.now()
            dtString = now.strftime('%H:%M:%S')
            f.writelines(f'\n{name};{dtString}')
                
encodeListknown = findEncodings(images)
print('encoding complete')

cap = cv2.VideoCapture(0)

while True:
    success, img = cap.read()
    imgS = cv2.resize(img,(0,0),None,0.25,0.25)
    imgS = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    
    facesCurFrame = face_recognition.face_locations(imgS)
    encodesCurFrame = face_recognition.face_encodings(imgS,facesCurFrame)
    
    for encodeFace,faceLoc in zip(encodesCurFrame,facesCurFrame):
        matches = face_recognition.compare_faces(encodeListknown,encodeFace)
        facedist = face_recognition.face_distance(encodeListknown,encodeFace)
        print(facedist)
        matchIndex = np.argmin(facedist)
        
        
        if matches[matchIndex]:
            name= classNames[matchIndex].upper()
            print(name)
            y1,x2,y2,x1 = faceLoc
            cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
            cv2.putText(img,name,(x1+6,y2-6),cv2.FONT_HERSHEY_COMPLEX,1,(255,255,255),2)
            markAttendance(name)


    cv2.imshow('webcam',img)
    cv2.waitKey(1)


['Amine Rhayem', 'billgates', 'Elon Musk']
encoding complete
[0.51417219 0.92229926 0.90834814]
AMINE RHAYEM
[0.50389309 0.91040649 0.89206017]
AMINE RHAYEM
[0.49519558 0.92470182 0.90577619]
AMINE RHAYEM
[0.48948333 0.90218808 0.88886629]
AMINE RHAYEM
[0.49900477 0.92701232 0.91346495]
AMINE RHAYEM
[0.51227075 0.90632809 0.90749524]
AMINE RHAYEM
[0.49291323 0.9040126  0.90270237]
AMINE RHAYEM
[0.51192302 0.90833851 0.90464208]
AMINE RHAYEM
[0.49836999 0.90557854 0.89682015]
AMINE RHAYEM
[0.46382833 0.89269455 0.887341  ]
AMINE RHAYEM
[0.4886506  0.90590578 0.91203078]
AMINE RHAYEM
[0.47508573 0.9034086  0.89984413]
AMINE RHAYEM
